#服务端口
server:
  port: 8761
#    是否注册自己
eureka:
  client:
    register-with-eureka: false
#    是否获取其他eureka同步
    fetch-registry: false
    #    注册中心访问地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


