server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
#    表示本地读取
  profiles:
    active: native
#      检索配置文件路径在哪里,resource目录/shared文件夹里
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#