server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
#检索大路径github
          uri: https://github.com/cgy5201314/Clouddemo.git
#检索小路径，用户名密码
          search-paths: config
          username: cgy5201314
          password: cgycgy200211
      label: master
eureka:
  client:
    serviceurl:
      defaultZone: http://localhost:8761/eureka/

